import os

env = Environment()

scrypt = env.StaticLibrary('scrypt', Glob('src/thirdparty/scrypt/*.c'), CFLAGS='-O3')

env.Command(['#/src/thirdparty/libsodium/dist/lib/libsodium.a', '#/src/thirdparty/libsodium/dist/include/sodium.h'],
    '#/src/thirdparty/libsodium/configure',
    'cd src/thirdparty/libsodium/ && ./configure --prefix=`pwd`/dist --enable-static --disable-shared && make && make install')

wuffcrypt = env.Program('wuffcrypt', [Glob('src/*.cpp'), scrypt, '#/src/thirdparty/libsodium/dist/lib/libsodium.a'],
    CCFLAGS='-std=c++11 -O2 -g -Wall -Wextra -Wshadow -Wno-unused-parameter',
    CPPPATH=['#/src/thirdparty/libsodium/dist/include/', '#/src/thirdparty/scrypt/'])
